driver=org.postgresql.Driver
classpath=src/main/resources
url=jdbc:postgresql://localhost:5432/dormitory_db
username=postgres
password=root
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml